In [1]:
import numpy as np
import pandas as pd
import math as m
from sklearn.naive_bayes import GaussianNB

In [2]:
df=pd.read_csv('mushroom2.csv')
N=df.iloc[:,1].size
border=m.ceil(0.8*N)
trGroup=df.iloc[0:border]
coGroup=df.iloc[border:N]

In [3]:
X=trGroup.iloc[:,1:4].to_numpy()
for i in range(X[:,0].size):
    if X[i,0]=='b':
        X[i,0]=1
    if X[i,0]=='c':
        X[i,0]=2
    if X[i,0]=='x':
        X[i,0]=3
    if X[i,0]=='f':
        X[i,0]=4
    if X[i,0]=='k':
        X[i,0]=5
    if X[i,0]=='s':
        X[i,0]=6
    #------------------
    if X[i,1]=='f':
        X[i,1]=1
    if X[i,1]=='g':
        X[i,1]=2
    if X[i,1]=='y':
        X[i,1]=3
    if X[i,1]=='s':
        X[i,1]=4
    #------------------
    if X[i,2]=='f':
        X[i,2]=1
    if X[i,2]=='t':
        X[i,2]=2
X=X.astype('int32')

In [4]:
print(X)

[[3 4 2]
 [3 4 2]
 [1 4 2]
 ...
 [4 4 1]
 [4 3 1]
 [4 4 1]]


In [5]:
Y=trGroup.iloc[:,0].to_numpy()
for i in range(Y.size):
    if Y[i]=='p':
        Y[i]=0
    if Y[i]=='e':
        Y[i]=1
Y=Y.astype('int32')

In [6]:
clf = GaussianNB()
clf.fit(X, Y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [7]:
M=0
for i in range(X[:,0].size):
    if clf.predict([X[i]])!=Y[i]:
        M=M+1
print('mistakes=',M,'   %.4f%%'%(100*M/X[:,0].size))

mistakes= 1566    24.0923%


In [8]:
X=coGroup.iloc[:,1:4].to_numpy()
for i in range(X[:,0].size):
    if X[i,0]=='b':
        X[i,0]=1
    if X[i,0]=='c':
        X[i,0]=2
    if X[i,0]=='x':
        X[i,0]=3
    if X[i,0]=='f':
        X[i,0]=4
    if X[i,0]=='k':
        X[i,0]=5
    if X[i,0]=='s':
        X[i,0]=6
    #------------------
    if X[i,1]=='f':
        X[i,1]=1
    if X[i,1]=='g':
        X[i,1]=2
    if X[i,1]=='y':
        X[i,1]=3
    if X[i,1]=='s':
        X[i,1]=4
    #------------------
    if X[i,2]=='f':
        X[i,2]=1
    if X[i,2]=='t':
        X[i,2]=2
X=X.astype('int32')

In [9]:
Y=coGroup.iloc[:,0].to_numpy()
for i in range(Y.size):
    if Y[i]=='p':
        Y[i]=0
    if Y[i]=='e':
        Y[i]=1
Y=Y.astype('int32')

In [10]:
M=0
for i in range(X[:,0].size):
    if clf.predict([X[i]])!=Y[i]:
        M=M+1
print('mistakes=',M,'   %.4f%%'%(100*M/X[:,0].size))

mistakes= 294    18.1034%
